INSERT INTO beginner.estabelecimentos (
    cnpj_basico,
    cnpj_ordem,
    cnpj_dv,
    identificador_matriz_filial,
    nome_fantasia,
    situacao_cadastral,
    data_situacao_cadastral,
    motivo_situacao_cadastral,
    nome_cidade_exterior,
    pais,
    data_inicio_atividade,
    cnae_fiscal_principal,
    cnae_fiscal_secundaria,
    tipo_logradouro,
    logradouro,
    numero,
    complemento,
    bairro,
    cep,
    uf,
    municipio,
    ddd1,
    telefone1,
    ddd2,
    telefone2,
    ddd_fax,
    fax,
    correio_eletronico,
    situacao_especial,
    data_situacao_especial
)
SELECT DISTINCT
    cnpj_basico::CHAR(8),
    cnpj_ordem::CHAR(4),
    cnpj_dv::CHAR(2),
    identificador_matriz_filial::SMALLINT,
    nome_fantasia::TEXT,
    situacao_cadastral::SMALLINT,
    data_situacao_cadastral::DATE,
    motivo_situacao_cadastral::INTEGER,
    nome_cidade_exterior::TEXT,
    pais::INTEGER,
    data_inicio_atividade::DATE,
    cnae_fiscal_principal::INTEGER,
    cnae_fiscal_secundaria::TEXT,
    tipo_logradouro::TEXT,
    logradouro::TEXT,
    numero::TEXT,
    complemento::TEXT,
    bairro::TEXT,
    cep::CHAR(8),
    uf::CHAR(2),
    municipio::INTEGER,
    ddd1::CHAR(2),
    telefone1::TEXT,
    ddd2::CHAR(2),
    telefone2::TEXT,
    ddd_fax::CHAR(2),
    fax::TEXT,
    correio_eletronico::TEXT,
    situacao_especial::TEXT,
    data_situacao_especial::DATE
FROM staging.estabelecimentos
WHERE cnpj_basico IS NOT NULL
  AND cnpj_ordem IS NOT NULL
  AND cnpj_dv IS NOT NULL
ON CONFLICT (cnpj_basico, cnpj_ordem, cnpj_dv) DO UPDATE
SET
    identificador_matriz_filial = EXCLUDED.identificador_matriz_filial,
    nome_fantasia = EXCLUDED.nome_fantasia,
    situacao_cadastral = EXCLUDED.situacao_cadastral,
    data_situacao_cadastral = EXCLUDED.data_situacao_cadastral,
    motivo_situacao_cadastral = EXCLUDED.motivo_situacao_cadastral,
    nome_cidade_exterior = EXCLUDED.nome_cidade_exterior,
    pais = EXCLUDED.pais,
    data_inicio_atividade = EXCLUDED.data_inicio_atividade,
    cnae_fiscal_principal = EXCLUDED.cnae_fiscal_principal,
    cnae_fiscal_secundaria = EXCLUDED.cnae_fiscal_secundaria,
    tipo_logradouro = EXCLUDED.tipo_logradouro,
    logradouro = EXCLUDED.logradouro,
    numero = EXCLUDED.numero,
    complemento = EXCLUDED.complemento,
    bairro = EXCLUDED.bairro,
    cep = EXCLUDED.cep,
    uf = EXCLUDED.uf,
    municipio = EXCLUDED.municipio,
    ddd1 = EXCLUDED.ddd1,
    telefone1 = EXCLUDED.telefone1,
    ddd2 = EXCLUDED.ddd2,
    telefone2 = EXCLUDED.telefone2,
    ddd_fax = EXCLUDED.ddd_fax,
    fax = EXCLUDED.fax,
    correio_eletronico = EXCLUDED.correio_eletronico,
    situacao_especial = EXCLUDED.situacao_especial,
    data_situacao_especial = EXCLUDED.data_situacao_especial
