[project]
name = "cnpj-etl"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "tqdm>=4.67.3",
]

[dependency-groups]
beginner = [
    "pandas>=2.3.3",
]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.15.1",
]
intermediate = [
    "apache-airflow>=3.1.7",
    "boto3>=1.42.52",
    "dbt-core>=1.11.6",
    "dbt-postgres>=1.10.0",
]
